# Use root as user credentials
# Before running compose-up command , create network. for example "docker network create mysql8"
version: "3.1"

services:
  default-db:
    container_name: default-db
    image: mysql:latest
    restart: always
    volumes:
      - ./db/default/data:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --transaction-isolation=READ-COMMITTED
    environment:
      MYSQL_ROOT_PASSWORD: default
    ports:
      - "3306:3306"
#  user-db:
#    container_name: user-db
#    image: mysql:latest
#    restart: always
#    volumes:
#      - ./db/user/data:/var/lib/mysql
#    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --transaction-isolation=READ-COMMITTED
#    environment:
#      MYSQL_ROOT_PASSWORD: user
#    ports:
#      - "3307:3306"
#  order-db:
#    container_name: order-db
#    image: mysql:latest
#    restart: always
#    volumes:
#      - ./db/order/data:/var/lib/mysql
#    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --transaction-isolation=READ-COMMITTED
#    environment:
#      MYSQL_ROOT_PASSWORD: order
#    ports:
#      - "3308:3306"
#  shop-db:
#    container_name: shop-db
#    image: mysql:latest
#    restart: always
#    volumes:
#      - ./db/shop/data:/var/lib/mysql
#    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --transaction-isolation=READ-COMMITTED
#    environment:
#      MYSQL_ROOT_PASSWORD: shop
#    ports:
#      - "3309:3306"
#  delivery-db:
#    container_name: delivery-db
#    image: mysql:latest
#    restart: always
#    volumes:
#      - ./db/delivery/data:/var/lib/mysql
#    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --transaction-isolation=READ-COMMITTED
#    environment:
#      MYSQL_ROOT_PASSWORD: delivery
#    ports:
#      - "3310:3306"
#  billing-db:
#    container_name: billing-db
#    image: mysql:latest
#    restart: always
#    volumes:
#      - ./db/billing/data:/var/lib/mysql
#    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --transaction-isolation=READ-COMMITTED
#    environment:
#      MYSQL_ROOT_PASSWORD: billing
#    ports:
#      - "3311:3306"
