# Use root as user credentials
# Before running compose-up command , create network. for example "docker network create mysql8"
version: "3.1"

services:
  default-db:
    container_name: default-db
    image: mysql:latest
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --transaction-isolation=READ-COMMITTED
    ports:
      - "3307:3306"
    volumes:
      - ./db/mysql/default/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: default
  default-redis:
    container_name: default-redis
    image: redis:latest
    restart: always
    command: redis-server --notify-keyspace-events Ex
    ports:
      - "6381:6379"
    volumes:
      - ./db/redis/default/data:/data
      - ./db/redis/default/redis.conf:/usr/local/etc/redis.conf