# Use root as user credentials
# Before running compose-up command , create network. for example "docker network create mysql8"
version: "3.1"

services:
  mysql-primary:
    container_name: mysql-primary
    image: mysql:latest
    platform: linux/x86_64
    restart: always
    volumes:
      - ./db/primary/data:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --transaction-isolation=READ-COMMITTED
    environment:
      MYSQL_ROOT_PASSWORD: primary
    ports:
      - 3307:3306
  mysql-replica:
    container_name: mysql-replica
    image: mysql:latest
    platform: linux/x86_64
    restart: always
    volumes:
      - ./db/replica/data:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --transaction-isolation=READ-COMMITTED
    environment:
      MYSQL_ROOT_PASSWORD: replica
    ports:
      - 3308:3306
