### asdf
POST {{url}}/api/v1/users
Content-Type: application/json

{
  "username": "test-name-{{$uuid}}",
  "userType": "NORMAL",
  "userPhoneNumber": "010{{$randomInt}}{{$randomInt}}{{$randomInt}}",
  "userAddress": "Gangseo-gu, Seoul, Republic of Korea"
}

### asdf
POST {{url}}/api/v1/authentication/users/1
