### Successful GET users: check response status is 200
GET {{url}}/api/v1/users

> {%
client.test("User found successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body["statusCode"] === "SUCCESS", "Response body.statusCode is not SUCCESS");
  client.assert(response.body["data"], "Response body.data is undefined");
  client.assert(response.body["data"].length > 0, "Response body.data.length is not greater than 0");
});
%}

### Successful POST users: check response status is 201
POST {{url}}/api/v1/users
Content-Type: application/json

{
  "username": "test-name-{{$uuid}}",
  "userType": "NORMAL",
  "userPhoneNumber": "010{{$randomInt}}{{$randomInt}}{{$randomInt}}",
  "userAddress": "Gangseo-gu, Seoul, Republic of Korea"
}

> {%
client.test("User created successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
  client.assert(response.body["statusCode"] === "SUCCESS", "Response body.statusCode is not SUCCESS");
  client.assert(response.body["data"]["id"], "Response body.data.id should not be undefined");
});
%}

### Failed POST users: check response status is 400
POST {{url}}/api/v1/users
Content-Type: application/json

{
  "username": "d",
  "userPhoneNumber": "0129222"
}

> {%
client.test("User created unsuccessfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
  client.assert(response.body["statusCode"] === "FAIL", "Response body.statusCode is not FAIL");
});
%}

### Failed POST users: check response status is 400
POST {{url}}/api/v1/users
Content-Type: application/json

{
  "userType": "NORMAL",
  "username": "test-name-{{$uuid}}",
  "userPhoneNumber": "010{{$randomInt}}{{$randomInt}}{{$randomInt}}",
  "userAddress": "Gangseo-gu, Seoul, Republic of Korea",
  "userGroupId": -1
}

> {%
client.test("User created unsuccessfully", function() {
  client.assert(response.status === 409, "Response status is not 409");
  client.assert(response.body["statusCode"] === "FAIL", "Response body.statusCode is not FAIL");
});
%}

