
spring:
  datasource:
    hikari:
      main:
        jdbc-url: jdbc:mysql://localhost:3307/jpa-test?useSSL=false&createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: main
      sub:
        jdbc-url: jdbc:mysql://localhost:3308/jpa-test?useSSL=false&createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: sub

#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.show-sql=true

#spring.jpa.database=mysql
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update
